version: '0.1'
paths:
  specs: .specwright/specs
  aips: .specwright/aips
repo:
  default_branch: main
user:
  default_owner: null
  default_tier: null
current:
  spec: .specwright/specs/domain-modular-architecture-refactor.md
  aip: /workspace/final-form/.specwright/aips/domain-modular-architecture-refactor.yaml
